sshwa: Refactor to use pure bash

diff --git a/misc/sshwa b/misc/sshwa
--- a/misc/sshwa
+++ b/misc/sshwa
@@ -1,46 +1,57 @@
 #!/usr/bin/env bash
 
-function show_help() {
-  name=$(basename ${0})
+show_help() {
+  name=$(basename "${0}")
   cat <<EOF
 ${name} will knock on port 22 of the given host
 and then SSH to the host once successful
 
 Usage:
   ${name} HOST
-  ${name} -h | -?
+  ${name} -h | --help | -?
 
 Options:
-  -h, -?  Show this help message
+  -h, --help, -?  Show this help message
 EOF
   exit 0
 }
 
 # Options parsing
-OPTIND=1
-while getopts ":h" opt; do
-  case "${opt}" in
-    h|\?)
+POSITIONAL=()
+while [[ $# -gt 0 ]]; do
+  case $1 in
+    -\?|-h|--help)
       show_help
-      exit 0
       ;;
+    *)
+      POSITIONAL+=("$1")
+      shift
   esac
 done
+set -- "${POSITIONAL[@]}"
 
-command -v "nc" >/dev/null 2>&1 || {
-  echo >&2 "nc is required to use this command!"
-  exit 1
+[[ $# -eq 0 ]] && show_help
+
+require() {
+  name="${2:-${1}}"
+  command -v "${1}" >/dev/null 2>&1 || {
+    printf 'The %s tool is required to use this script!\n' "${name}" >&2
+    [[ -z "${3}" ]] || printf '\tSee: %s\n' "${3}" >&2
+    exit 1
+  }
 }
 
-echo -n "Knocking on ${1}..."
+require 'nc'
+require 'sleep'
+require 'ssh'
 
+printf 'Knocking on %s...' "${1}"
 until nc -vzw 2 "${1}" 22 2>/dev/null; do
   sleep 2
-  echo -n .
+  printf '.'
 done
 
-echo -e " \033[1;32mAnswered!\033[0;39m"
-
+printf ' \033[1;32mAnswered!\033[0;39m\n'
 ssh "${1}"
 
 exit 0
