dbenc: Refactor to use pure bash

diff --git a/chef/dbenc b/chef/dbenc
--- a/chef/dbenc
+++ b/chef/dbenc
@@ -1,37 +1,47 @@
 #!/usr/bin/env bash
+# shellcheck disable=SC1117
 
-function show_help() {
-  name=$(basename ${0})
+basename() {
+  : "${1%/}"
+  printf '%s\n' "${_##*/}"
+}
+
+show_help() {
+  name=$(basename "${0}")
   cat <<EOF
+${name} toggles and audits encryption for Chef data bags
+
 Usage:
-  ${name} [check]             Displays whether databag encryption is enabled
+  ${name} [check]             Displas whether databag encryption is enabled
   ${name} toggle              Toggles automatic databag encryption
-  ${name} audit [bag] [item]  Displays whether (the given) data bag(s) are encrypted
-  ${name} -h | -?
+  ${name} audit [BAG [ITEM]]  Displays whether (the given) data bag(s) are encrypted
+  ${name} -h | --help | -?
 
 Options:
-  -h, -?  Show this help message
+  -h, --help, -?  Show this help message
 EOF
   exit 0
 }
 
-# Reset getopts for the shell
-OPTIND=1
-
 # Options parsing
-while getopts "h?" opt; do
-  case "${opt}" in
-    h|\?)
+POSITIONAL=()
+while [[ $# -gt 0 ]]; do
+  case $1 in
+    -\?|-h|--help)
       show_help
       exit 0
       ;;
+    *)
+      POSITIONAL+=("$1")
+      shift
   esac
 done
+set -- "${POSITIONAL[@]}"
 
 knife_config="${HOME}/.chef/knife.rb"
 
 if [ ! -f "${knife_config}" ]; then
-  echo "${knife_config} not found!"
+  printf '%s not found!' "${knife_config}"
   exit 1
 fi
 
@@ -43,25 +53,25 @@ edbs_disabled="${disabled_prefix}encrypted_data_bag_secret"
 ksf_enabled="${base_prefix}knife\[:secret_file]"
 ksf_disabled="${disabled_prefix}knife\[:secret_file]"
 
-function check_encryption() {
+check_encryption() {
   if grep -q "${edbs_disabled}" "${knife_config}"; then
     if grep -q "${ksf_disabled}" "${knife_config}"; then
-      echo "Encryption disabled!"
+      printf "Encryption disabled!\n"
     else
-      echo "Encryption mismatch!"
+      printf "Encryption mismatch!\n"
     fi
   elif grep -q "${edbs_enabled}" "${knife_config}"; then
     if grep -q "${ksf_enabled}" "${knife_config}"; then
-      echo "Encryption enabled!"
+      printf "Encryption enabled!\n"
     else
-      echo "Encryption mismatch!"
+      printf "Encryption mismatch!\n"
     fi
   else
-    echo "Encryption state unknown!"
+    printf "Encryption state unknown!\n"
   fi
 }
 
-function toggle_encryption() {
+toggle_encryption() {
   state=$(check_encryption | awk '{print $2}' | tr -d '!$')
 
   if [ "${state}" == "disabled" ]; then
@@ -73,39 +83,40 @@ function toggle_encryption() {
     sed -i '' "s/${ksf_enabled}/# knife\[:secret_file]/" "${knife_config}"
     check_encryption
   else
-    echo >&2 "Unable to toggle! [$(check_encryption)]"
+    printf 'Unable to toggle! [%s]' "$(check_encryption)" >&2
     exit 1
   fi
 }
 
-function check_knife() {
+check_knife() {
   command -v "knife" >/dev/null 2>&1 || {
-    echo >&2 "knife is required to use this command!"
+    printf 'knife is required to use this command!' >&2
     exit 1
   }
+
 }
 
-function audit_encryption() {
+audit_encryption() {
   initial_state=$(check_encryption | awk '{print $2}' | tr -d '!$')
 
   if [ "${initial_state}" != "disabled" ]; then
     toggle_encryption
-    echo
+    printf '\n'
   fi
 
   item="${2}"
 
   for bag in ${1:-$(knife data bag list 2>/dev/null)}; do
     for item in ${2:-$(knife data bag show "${bag}" 2>/dev/null)}; do
-      echo -n "Checking ${bag}/${item}... "
+      printf 'Checking %s/%s... ' "${bag}" "${item}"
 
       if knife data bag show "${bag}" "${item}" 2>/dev/null | grep -q encrypted_data; then
-        echo -e "\033[1;32mEncrypted!\033[0;39m"
+        printf '\033[1;32mEncrypted!\033[0;39m\n'
       else
-        echo -e "\033[1;31mNOT encrypted!\033[0;39m"
+        printf '\033[1;31mNOT encrypted!\033[0;39m\n'
       fi
     done
-    echo
+    printf '\n'
   done
 
   if [ "${initial_state}" != "disabled" ]; then
@@ -118,7 +129,7 @@ case "${1}" in
     toggle_encryption
     exit 0
     ;;
-  check|"")
+  check|'')
     check_encryption
     exit 0
     ;;
@@ -128,7 +139,7 @@ case "${1}" in
     exit 0
     ;;
   *)
-    echo >&2 "Unknown command: ${1}"
+    printf 'Unknown command: %s' "${1}" >&2
     exit 1
     ;;
 esac
